### ISSUE TITLE
BaM message error 

### ISSUE THREAD

**Issue by Felipemendezrios** [Felipemendezrios/RatingShiftHappens#9]
I have included a new dataset containing annual minimum stage data for the Ardeche River at Meyras. 

Upon running the recursive segmentation using the following code:
results=recursive.segmentation(obs=ArdecheRiver$H,time=ArdecheRiver$Year,u=ArdecheRiver$uH,nSmax=3)

I found this message error :
BaM: a FATAL ERROR has occured:
 Config_Read_RemnantSigma:Config_Read_RemnantSigma_engine:Config_Read_Par:ReadError
 Execution will stop

Despite this error message, all calculations were completed. Hence, I believe it's an annoying but non-blocking error message, rather than a bug per se.

**Comment by benRenard** [comment]
Fixed by commit e186f61
